version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env
    container_name: estivales_app_dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - estivales_dev

  db:
    image: mysql:8
    container_name: estivales_db_dev
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - estivales_dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: estivales_phpmyadmin_dev
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - estivales_dev

volumes:
  mysql_data_dev:

networks:
  estivales_dev:
    driver: bridge