#FROM node:20-alpine
#
#WORKDIR /app
#
#RUN apk add --no-cache git
#
#COPY package*.json ./
#
#RUN npm install --os=linux --libc=musl sharp
#
#EXPOSE 3000
#
#COPY entrypoint.sh /entrypoint.sh
#
#RUN chmod +x /entrypoint.sh
#
#CMD ["/entrypoint.sh"]
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances du projet (dont Next.js)
RUN npm install

# Installer sharp de manière adaptée à Alpine (si nécessaire en plus)
RUN npm install --os=linux --libc=musl sharp

# Copier le reste du code de l'app
COPY . .

EXPOSE 3000

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
